# http://blog.onk.ninja/2015/10/27/rubocop-getting-started
# https://gist.github.com/onk/38bfbd78899d892e0e83

Rails:
  Enabled: true

AllCops:
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'
    - 'Gemfile'
    - 'Guardfile'
    - 'Rakefile'

Style/AsciiComments:
  Enabled: false

Style/CommentAnnotation:
  Enabled: false

Style/Documentation:
  Enabled: false

Layout/SpaceBeforeFirstArg:
  Enabled: false

LineLength:
  Max: 160

MethodLength:
  Max: 12
