language: ruby
rvm:
  - 2.3.1
bundler_args: --jobs=2
env:
  - DB=postgresql
script:
  - RAILS_ENV=test bundle exec rake db:reset --trace
  - bundle exec rake
branches:
  only:
    - master
services:
  - elasticsearch
