env:
  global:
    - CC_TEST_REPORTER_ID=c6b361d7bddeefccad59e82272a3d861675625ff7b3a0d9236b9c7b54fcdbaab
    - DB=postgresql
language: ruby
rvm:
  - 2.5.1
bundler_args: --jobs=2
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - RAILS_ENV=test bundle exec rails db:reset --trace
  - bundle exec rspec
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
branches:
  only:
    - master
services:
  - elasticsearch
